{"name": "Invalid login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: chrome=134.0.6998.89)\nStacktrace:\n\tGetHandleVerifier [0x00D2B5A3+24387]\n\t(No symbol) [0x00CB5904]\n\t(No symbol) [0x00B90753]\n\t(No symbol) [0x00B8DB9E]\n\t(No symbol) [0x00B814B8]\n\t(No symbol) [0x00B82DC0]\n\t(No symbol) [0x00B81747]\n\t(No symbol) [0x00B812A3]\n\t(No symbol) [0x00B80FB1]\n\t(No symbol) [0x00B7EE80]\n\t(No symbol) [0x00B7F91B]\n\t(No symbol) [0x00B9420E]\n\t(No symbol) [0x00C1FDE7]\n\t(No symbol) [0x00BFD84C]\n\t(No symbol) [0x00C1F138]\n\t(No symbol) [0x00BFD646]\n\t(No symbol) [0x00BCC59F]\n\t(No symbol) [0x00BCD8E4]\n\tGetHandleVerifier [0x0102D883+3179043]\n\tGetHandleVerifier [0x01046CF9+3282585]\n\tGetHandleVerifier [0x0104167C+3260444]\n\tGetHandleVerifier [0x00DC4330+650448]\n\t(No symbol) [0x00CBED0D]\n\t(No symbol) [0x00CBBAF8]\n\t(No symbol) [0x00CBBC99]\n\t(No symbol) [0x00CAE530]\n\tBaseThreadInitThunk [0x766A5D49+25]\n\tRtlInitializeExceptionChain [0x7753CE3B+107]\n\tRtlGetAppContainerNamedObjectPath [0x7753CDC1+561]\n\n", "trace": "  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\example_steps.py\", line 8, in step_open_browser\n    context.driver.get(\"https://practicetestautomation.com/practice-test-login/\")\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I open the browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n  (Session info: chrome=134.0.6998.89)\nStacktrace:\n\tGetHandleVerifier [0x00D2B5A3+24387]\n\t(No symbol) [0x00CB5904]\n\t(No symbol) [0x00B90753]\n\t(No symbol) [0x00B8DB9E]\n\t(No symbol) [0x00B814B8]\n\t(No symbol) [0x00B82DC0]\n\t(No symbol) [0x00B81747]\n\t(No symbol) [0x00B812A3]\n\t(No symbol) [0x00B80FB1]\n\t(No symbol) [0x00B7EE80]\n\t(No symbol) [0x00B7F91B]\n\t(No symbol) [0x00B9420E]\n\t(No symbol) [0x00C1FDE7]\n\t(No symbol) [0x00BFD84C]\n\t(No symbol) [0x00C1F138]\n\t(No symbol) [0x00BFD646]\n\t(No symbol) [0x00BCC59F]\n\t(No symbol) [0x00BCD8E4]\n\tGetHandleVerifier [0x0102D883+3179043]\n\tGetHandleVerifier [0x01046CF9+3282585]\n\tGetHandleVerifier [0x0104167C+3260444]\n\tGetHandleVerifier [0x00DC4330+650448]\n\t(No symbol) [0x00CBED0D]\n\t(No symbol) [0x00CBBAF8]\n\t(No symbol) [0x00CBBC99]\n\t(No symbol) [0x00CAE530]\n\tBaseThreadInitThunk [0x766A5D49+25]\n\tRtlInitializeExceptionChain [0x7753CE3B+107]\n\tRtlGetAppContainerNamedObjectPath [0x7753CDC1+561]\n\n", "trace": "  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\example_steps.py\", line 8, in step_open_browser\n    context.driver.get(\"https://practicetestautomation.com/practice-test-login/\")\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742202685379, "stop": 1742202727743}, {"name": "When I enter the username \"student\"", "status": "skipped", "start": 1742202727748, "stop": 1742202727748}, {"name": "And I enter the password \"Password123\"", "status": "skipped", "start": 1742202727748, "stop": 1742202727748}, {"name": "And I click the login button", "status": "skipped", "start": 1742202727748, "stop": 1742202727748}, {"name": "Then I should see the success message \"Invalid login\"", "status": "skipped", "start": 1742202727748, "stop": 1742202727748}], "start": 1742202685354, "stop": 1742202727748, "uuid": "ce841f5b-f97b-4365-b64f-b46d42ad9712", "historyId": "35890fcf46fa3dcb90b7287fed59418a", "fullName": "Login and Navigate to Pages: Invalid login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login and Navigate to Pages"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}